import { NextRequest, NextResponse } from "next/server";
import React from "react";
import { renderToBuffer, Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { DiagnosticReport, ScoreCard } from "@/lib/types";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10, color: "#16241f" },
  title: { fontFamily: "Helvetica-Bold", fontSize: 22, marginBottom: 4 },
  subtitle: { fontSize: 10, color: "#2c3f37", marginBottom: 20 },
  sectionTitle: { fontFamily: "Helvetica-Bold", fontSize: 14, marginTop: 18, marginBottom: 8 },
  card: {
    borderWidth: 1,
    borderColor: "#d9d0bd",
    borderRadius: 4,
    padding: 10,
    marginBottom: 8,
  },
  cardHeader: { flexDirection: "row", justifyContent: "space-between", marginBottom: 4 },
  cardTitle: { fontFamily: "Helvetica-Bold", fontSize: 11 },
  cardScore: { fontFamily: "Helvetica-Bold", fontSize: 14 },
  cardSummary: { fontSize: 9, color: "#2c3f37", marginBottom: 4 },
  detail: { fontSize: 8.5, color: "#2c3f37", marginBottom: 2 },
  roadmapItem: { flexDirection: "row", marginBottom: 8 },
  roadmapNum: { fontFamily: "Helvetica-Bold", fontSize: 14, width: 24 },
  avoidItem: { fontSize: 9, marginBottom: 6, color: "#b0432f" },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, fontSize: 7, color: "#8a8474" },
});

function statusColor(status: ScoreCard["status"]) {
  switch (status) {
    case "good":
      return "#2f6f62";
    case "warning":
      return "#c9852c";
    case "critical":
      return "#b0432f";
    default:
      return "#4a5d99";
  }
}

function ReportDocument({ report }: { report: DiagnosticReport }) {
  const measurable = report.cards.filter((c) => c.score !== null);
  const overallScore = measurable.length
    ? Math.round(measurable.reduce((s, c) => s + (c.score ?? 0), 0) / measurable.length)
    : null;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{report.input.businessType} — Marketing Diagnostic</Text>
        <Text style={styles.subtitle}>
          {report.input.websiteUrl} · Generated {new Date(report.generatedAt).toLocaleDateString()}
          {overallScore !== null ? ` · Overall score: ${overallScore}/100` : ""}
        </Text>

        {report.recommendedChannel.channel !== "N/A" && (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>Recommended Channel: {report.recommendedChannel.channel}</Text>
            <Text style={styles.cardSummary}>{report.recommendedChannel.reasoning}</Text>
            <Text style={styles.detail}>Budget fit: {report.recommendedChannel.budgetFit}</Text>
          </View>
        )}

        <Text style={styles.sectionTitle}>Diagnostic Scorecards</Text>
        {report.cards.map((card) => (
          <View key={card.id} style={styles.card} wrap={false}>
            <View style={styles.cardHeader}>
              <Text style={styles.cardTitle}>{card.title}</Text>
              {card.score !== null && (
                <Text style={{ ...styles.cardScore, color: statusColor(card.status) }}>
                  {card.score}/100
                </Text>
              )}
            </View>
            <Text style={styles.cardSummary}>{card.summary}</Text>
            {card.details.slice(0, 4).map((d, i) => (
              <Text key={i} style={styles.detail}>
                • {d}
              </Text>
            ))}
          </View>
        ))}

        {report.roadmap.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Priority Roadmap</Text>
            {report.roadmap
              .sort((a, b) => a.priority - b.priority)
              .map((r) => (
                <View key={r.priority} style={styles.roadmapItem}>
                  <Text style={styles.roadmapNum}>{r.priority}</Text>
                  <View>
                    <Text style={{ fontFamily: "Helvetica-Bold", fontSize: 10 }}>{r.action}</Text>
                    <Text style={styles.detail}>{r.why}</Text>
                  </View>
                </View>
              ))}
          </>
        )}

        {report.avoidList.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>What To Avoid Right Now</Text>
            {report.avoidList.map((a, i) => (
              <Text key={i} style={styles.avoidItem}>
                • {a}
              </Text>
            ))}
          </>
        )}

        <Text style={styles.footer}>
          Generated by Business Marketing Diagnostic. Live-data scores (domain, SSL, SEO, mobile) are
          pulled directly from the website and public APIs at the time of the report; re-running the
          report later will reflect any real changes to the site.
        </Text>
      </Page>
    </Document>
  );
}

export async function POST(req: NextRequest) {
  const report: DiagnosticReport = await req.json();

  const buffer = await renderToBuffer(<ReportDocument report={report} />);

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="diagnostic-report.pdf"`,
    },
  });
}
